version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: api-nestjs-postgres-pymes
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: bd-pymes
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
